### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [cmaddox5/Splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by cmaddox5** [comment]
Hi Billy!

I added the meta tag like you suggested. It does look much better on mobile now. Now I just need to tweak font sizes to make it look a little better. It has a problem now where if the quote is too long it overlaps the footer text.

If you have any other suggestions let me know. And thank you for the feedback!

**Comment by BillyMassey** [comment]
Good stuff Christian!

Good thought on changing the font. Perfecting page specific CSS can be a bit like going down a rabbit hole at times, so I wouldn't spend to much time on it if the font change doesn't work. You can always come back to it later and apply all the new stuff your learned from building the next apps. 

Great job finding the meta tag though! Keep up the awesome work :)
